In [1]:
import pandas as pd
import numpy as np

import constantes as const
from loader import cargar_dataset

### Carga del Dataset

In [2]:
df = cargar_dataset(const.PATH_DF_PROCESADO)

In [3]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,hrMedia,racha,hrMax,hrMin,lon,lat
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,19.8,0.0,16.0,23.5,6.7,3.5,90.0,<NA>,<NA>,<NA>,-13.863056,28.444722
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,4.0,0.0,0.0,8.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7.510833,42.531667
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,-5.0,0.4,-7.0,-3.0,3.1,1.5,100.0,<NA>,<NA>,<NA>,-4.010556,40.793056
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,4.3,2.6,2.0,6.6,0.0,0.0,90.0,7.2,<NA>,<NA>,-6.044167,43.566944
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,5.5,0.0,0.6,10.4,1.7,8.0,72.0,<NA>,<NA>,<NA>,1.163611,41.145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7424496,2024-12-31,9562X,MORELLA,CASTELLON,990,4.8,0.0,0.8,8.8,1.4,<NA>,85.0,5.0,97.0,63.0,-0.101944,40.621667
7424497,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,4.2,0.0,-4.9,13.4,0.0,<NA>,81.0,3.1,100.0,50.0,-1.543056,43.135833
7424498,2024-12-31,3254Y,MORA,TOLEDO,717,2.0,0.0,-3.1,7.1,1.1,<NA>,94.0,3.9,100.0,80.0,-3.780556,39.686944
7424499,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,92.0,<NA>,<NA>,<NA>,1.885,41.408056
7424500,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,4.1,0.0,-1.8,10.0,1.4,<NA>,80.0,6.1,97.0,62.0,-2.76,39.656111

In [4]:
df.dtypes

fecha         datetime64[ns]
indicativo    string[python]
nombre        string[python]
provincia     string[python]
altitud                Int64
tmed                 Float64
prec                 Float64
tmin                 Float64
tmax                 Float64
velmedia             Float64
sol                  Float64
hrMedia              Float64
racha                Float64
hrMax                Float64
hrMin                Float64
lon                  Float64
lat                  Float64
dtype: object

### Reestructuración en formato tidy data

In [5]:
df_tidy = df.copy(deep = True)

In [6]:
# Despivotamos las columnas con las variables, convirtiéndolas en pares variable - valor
df_tidy = df_tidy.melt(
    id_vars = [const.COL_FECHA] + const.COLS_LOCALIZACION,
    value_vars = const.COLS_VARIABLES,
    var_name = const.COL_VAR,
    value_name = const.COL_VAL
)

In [7]:
# Limpiamos todas aquellas que no tengan valor
df_tidy = df_tidy.dropna(subset=[const.COL_VAL])

In [8]:
display(df_tidy.sample(20))

,fecha,nombre,provincia,variable,valor
40650605,2012-05-17,ARICO,SANTA CRUZ DE TENERIFE,racha,8.9
3618695,2012-09-12,ESPIEL,CORDOBA,tmax,35.1
26682850,2015-05-24,STA.CRUZ DE TENERIFE,SANTA CRUZ DE TENERIFE,sol,9.9
42214639,2017-08-14,FRAGA,HUESCA,racha,13.9
4756094,2016-07-12,BENAHAVÍS,MALAGA,tmax,38.6
42064510,2017-02-18,VALVERDE DEL FRESNO,CACERES,racha,10.8
4855452,2016-11-07,SEGOVIA,SEGOVIA,tmax,5.1
20035115,2017-12-02,SEGOVIA,SEGOVIA,tmin,-3.3
34942374,2018-02-09,CAÑAVERAL,CACERES,velmedia,2.5
29868826,1974-04-24,"ÁVILA, AYUNTAMIENTO",AVILA,velmedia,2.2
7483104,1971-07-30,"VALLE DE HECHO, HECHO",HUESCA,tmed,23.5
47688713,2010-12-13,"BAZTAN, IRURITA",NAVARRA,hrMax,93.0
64889549,2018-11-30,TEMBLEQUE,TOLEDO,hrMin,59.0
45779594,1994-08-30,VILLARDECIERVOS,ZAMORA,hrMax,97.0
39467580,2006-10-11,BARCELONA AEROPUERTO,BARCELONA,racha,21.1
4357573,2015-03-23,RIBADAVIA,OURENSE,tmax,14.3
47756778,2011-03-18,TARANCÓN,CUENCA,hrMax,86.0
67095634,1976-08-09,PALACIOS DE LA SIERRA,BURGOS,prec,0.0
621663,1984-01-12,SAN JAVIER AEROPUERTO,MURCIA,tmax,18.4
12522128,2017-08-20,ARTÀ,ILLES BALEARS,tmed,23.4

In [9]:
df_tidy.to_csv(const.PATH_DF_TIDY, sep = ';', index = False)