In [1]:
import pandas as pd
import numpy as np

In [2]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024_con_Coordenadas.csv'

In [3]:
COLS_NOMBRES = [
    'indicativo',
    'nombre',
    'provincia',
]

COLS_INTS = [
    'altitud'
]

COLS_FLOATS = [
    'tmed',
    'prec',
    'tmin',
    'tmax',
    'velmedia',
    'sol',
    'presMax',
    'presMin',
    'hrMedia',
    'dir',
    'racha',
    'hrMax',
    'hrMin'
]

COLS_NUMS = COLS_INTS + COLS_FLOATS

COL_FECHA = 'fecha'
COLS_HORAS = [
    'horaPresMax',
    'horaPresMin',
    'horatmin',
    'horatmax',
    'horaracha',
    'horaHrMax',
    'horaHrMin'
]

COLS_COORDS = [
    'lat',
    'lon'
]

In [4]:
df = pd.read_csv(PATH_VAL_CLIM,
                 sep=';', decimal = ',',
                 dtype = {nombre: 'string' for nombre in COLS_NOMBRES} |
                         {entero: 'Int64' for entero in COLS_INTS} |
                         {coordenada: 'Float64' for coordenada in COLS_COORDS} |
                         {otros: 'object' for otros in COLS_FLOATS + COLS_HORAS},
                         # {decimal: 'Float64' for decimal in COLS_FLOATS if decimal != 'prec'},
                 parse_dates = [COL_FECHA])

In [5]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,horatmax,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin,lon,lat
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,"19,8","0,0","16,0","23,5","6,7",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.863056,28.444722
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,"4,0","0,0","0,0","8,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.510833,42.531667
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,"-5,0","0,4","-7,0","-3,0","3,1",...,15:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.010556,40.793056
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,"4,3","2,6","2,0","6,6","0,0",...,01:00,99.0,"7,2",00:13,NaN,NaN,NaN,NaN,-6.044167,43.566944
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,"5,5","0,0","0,6","10,4","1,7",...,14:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.163611,41.145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7427566,2024-12-31,9562X,MORELLA,CASTELLON,990,"4,8","0,0","0,8","8,8","1,4",...,13:42,12.0,"5,0",16:50,97.0,23:50,63.0,14:00,-0.101944,40.621667
7427567,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,"4,2","0,0","-4,9","13,4","0,0",...,14:50,22.0,"3,1",16:20,100.0,09:00,50.0,14:10,-1.543056,43.135833
7427568,2024-12-31,3254Y,MORA,TOLEDO,717,"2,0","0,0","-3,1","7,1","1,1",...,11:18,20.0,"3,9",14:30,100.0,09:20,80.0,11:20,-3.780556,39.686944
7427569,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,NaN,"0,0",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.885,41.408056
7427570,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,"4,1","0,0","-1,8","10,0","1,4",...,14:25,99.0,"6,1",Varias,97.0,09:00,62.0,15:50,-2.76,39.656111

### Preprocesado del Dataframe

In [6]:
df_prep = df.copy(deep = True)

In [7]:
COL_PREC = 'prec'
# df_prep.loc[df[COL_PREC] == 'Ip', COL_PREC] = 0
df_prep = df_prep[df_prep[COL_PREC] != 'Acum']
df_prep[COL_PREC] = df_prep[COL_PREC].replace('Ip', 0)

In [8]:
# Reemplazamos las comas por puntos para poder cargar los números como decimales (floats)
df_prep[COLS_FLOATS] = df_prep[COLS_FLOATS].replace(',', '.', regex=True).apply(pd.to_numeric, errors = 'raise')

In [9]:
df_prep.dtypes

fecha          datetime64[ns]
indicativo     string[python]
nombre         string[python]
provincia      string[python]
altitud                 Int64
tmed                  float64
prec                  float64
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia               float64
horatmin               object
horatmax               object
dir                   float64
racha                 float64
horaracha              object
hrMax                 float64
horaHrMax              object
hrMin                 float64
horaHrMin              object
lon                   Float64
lat                   Float64
dtype: object

In [10]:
# Corregimos inconsistencias en nombres de provincias
df_prep.loc[df_prep['provincia'] == 'BALEARES', 'provincia'] = 'ILLES BALEARS'
df_prep.loc[df_prep['provincia'] == 'SANTA CRUZ DE TENERIFE', 'provincia'] = 'STA. CRUZ DE TENERIFE'

In [11]:
# Borramos dos datos de una medición anómala
df_prep.loc[
    (df_prep['indicativo'] == '6084X') &
    (df_prep['tmin'] == 50.0) &
    (df_prep['tmax'] == -50.0),
    ['tmax', 'tmin']
] = np.nan

In [12]:
# Procesamos dirección del viento (según la info proporcionada en el fichero de metadatos)
dict_dir = {
    88: 'Desconocida',
    99: 'Varias'
}
dir_por_defecto = 'Válida'

df_prep['dir_tipo'] = df_prep['dir'].map(dict_dir).fillna(dir_por_defecto)

In [13]:
# Añadimos el sufijo :00 a las columnas cuyos valores carecen de él
cols_sufijo = ['horaPresMax', 'horaPresMin']
df_prep[cols_sufijo] = df_prep[cols_sufijo].where(
    df_prep[cols_sufijo].isna() | (df_prep[cols_sufijo] == 'Varias'),
    df_prep[cols_sufijo] + ':00'
)

In [14]:
df_prep.sample(20)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin,lon,lat,dir_tipo
2433168,2007-05-28,1639X,CHANDREXA DE QUEIXA,OURENSE,990,8.4,0.0,3.6,13.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.383611,42.260278,Válida
4796258,2016-08-25,3455X,JARAICEJO,CACERES,559,28.7,0.0,21.9,35.5,3.6,...,9.0,11.4,15:30,46.0,06:20,21.0,17:50,-5.808333,39.67,Válida
4612373,2016-01-19,2422,VALLADOLID,VALLADOLID,734,1.4,0.0,-1.9,4.7,0.8,...,24.0,5.8,02:30,100.0,Varias,87.0,15:10,-4.754167,41.640833,Válida
3616509,2012-09-05,6076X,"MARBELLA, PUERTO",MALAGA,2,23.4,0.0,20.9,25.8,5.0,...,6.0,8.3,06:40,82.0,19:40,60.0,02:30,-4.953056,36.484444,Válida
7287483,2024-07-26,8008Y,VILLENA,ALICANTE,486,25.0,0.0,16.8,33.2,4.4,...,16.0,11.7,13:30,94.0,06:00,27.0,12:20,-0.865556,38.576944,Válida
1491650,1998-03-07,8096,CUENCA,CUENCA,949,11.8,0.0,3.5,20.0,0.3,...,27.0,6.7,16:00,NaN,NaN,NaN,NaN,-2.131944,40.067222,Válida
6936245,2023-06-25,7012C,CARTAGENA,MURCIA,17,26.3,0.0,21.8,30.8,1.4,...,21.0,5.6,16:40,69.0,22:50,38.0,10:00,-0.987778,37.601111,Válida
6355162,2021-08-27,4497X,VILLANUEVA DEL FRESNO,BADAJOZ,247,23.0,0.0,16.1,30.0,2.8,...,28.0,10.3,15:10,85.0,06:30,38.0,16:10,-7.158056,38.372222,Válida
1068390,1992-03-20,7209,LORCA,MURCIA,312,13.0,0.0,5.2,20.8,1.1,...,23.0,8.6,14:10,99.0,Varias,38.0,12:35,-1.687222,37.654722,Válida
1248008,1994-11-09,1249I,OVIEDO,ASTURIAS,336,13.6,2.0,9.9,17.4,6.4,...,25.0,21.7,13:28,NaN,NaN,NaN,NaN,-5.874167,43.353333,Válida
889326,1989-03-27,9677,PORT AINÉ,LLEIDA,2410,5.5,0.0,2.5,8.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.214722,42.41,Válida
4872260,2016-11-24,2811A,NAVARREDONDA DE GREDOS,AVILA,1525,-0.4,1.8,-2.5,1.6,0.8,...,11.0,7.8,22:30,97.0,08:40,74.0,23:50,-5.143056,40.350556,Válida
940624,1990-02-11,3103,PANTANO EL VADO,GUADALAJARA,910,9.5,0.0,5.0,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.301944,41.003611,Válida
5014841,2017-05-11,B656A,SANTA MARÍA DEL CAMÍ,ILLES BALEARS,121,19.7,0.0,14.5,24.9,5.3,...,23.0,11.7,14:00,95.0,Varias,42.0,09:50,2.800278,39.6525,Válida
4439406,2015-06-25,6057X,MANILVA,MALAGA,140,22.0,0.0,18.6,25.3,3.9,...,12.0,9.7,06:10,92.0,05:10,66.0,12:10,-5.26,36.378333,Válida
7265955,2024-07-01,C406G,"LA OROTAVA, CAÑADAS TEIDE",STA. CRUZ DE TENERIFE,2150,18.1,0.0,9.1,27.1,2.2,...,99.0,8.3,Varias,34.0,20:40,6.0,07:00,-16.626111,28.224167,Varias
1669385,2000-06-09,0076,BARCELONA AEROPUERTO,BARCELONA,4,19.8,5.4,16.0,23.6,3.9,...,10.0,12.5,23:15,NaN,NaN,NaN,NaN,2.07,41.292778,Válida
2610704,2008-08-30,6143X,COÍN,MALAGA,230,24.8,0.0,19.6,29.9,NaN,...,NaN,NaN,NaN,89.0,04:57,45.0,17:20,-4.760833,36.657778,Válida
1856825,2002-08-08,9201K,JACA,HUESCA,823,16.2,NaN,10.7,21.8,3.9,...,2.0,15.0,15:10,NaN,NaN,NaN,NaN,-0.546944,42.578889,Válida
2432232,2007-05-25,5624X,AGUILAR DE LA FRONTERA,CORDOBA,309,16.4,NaN,11.4,21.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.685833,37.481944,Válida

In [15]:
df_prep.to_csv('Valores_Climatologicos_1970_2024_Limpios.csv', sep = ';', index = False)