In [1]:
import pandas as pd
import numpy as np

from loader import cargar_dataset

### Carga del Dataset

In [2]:
df = cargar_dataset('Valores_Climatologicos_1970_2024_Limpios.csv')

In [3]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,presMax,presMin,hrMedia,dir,racha,hrMax,hrMin,lon,lat
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,19.8,0.0,16.0,23.5,6.7,3.5,1006.3,1003.5,90.0,<NA>,<NA>,<NA>,<NA>,-13.863056,28.444722
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,4.0,0.0,0.0,8.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,-7.510833,42.531667
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,-5.0,0.4,-7.0,-3.0,3.1,1.5,800.9,792.5,100.0,<NA>,<NA>,<NA>,<NA>,-4.010556,40.793056
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,4.3,2.6,2.0,6.6,0.0,0.0,994.6,985.0,90.0,99.0,7.2,<NA>,<NA>,-6.044167,43.566944
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,5.5,0.0,0.6,10.4,1.7,8.0,997.3,989.0,72.0,<NA>,<NA>,<NA>,<NA>,1.163611,41.145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7424496,2024-12-31,9562X,MORELLA,CASTELLON,990,4.8,0.0,0.8,8.8,1.4,<NA>,<NA>,<NA>,85.0,12.0,5.0,97.0,63.0,-0.101944,40.621667
7424497,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,4.2,0.0,-4.9,13.4,0.0,<NA>,<NA>,<NA>,81.0,22.0,3.1,100.0,50.0,-1.543056,43.135833
7424498,2024-12-31,3254Y,MORA,TOLEDO,717,2.0,0.0,-3.1,7.1,1.1,<NA>,<NA>,<NA>,94.0,20.0,3.9,100.0,80.0,-3.780556,39.686944
7424499,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,92.0,<NA>,<NA>,<NA>,<NA>,1.885,41.408056
7424500,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,4.1,0.0,-1.8,10.0,1.4,<NA>,<NA>,<NA>,80.0,99.0,6.1,97.0,62.0,-2.76,39.656111

In [4]:
df.dtypes

fecha         datetime64[ns]
indicativo    string[python]
nombre        string[python]
provincia     string[python]
altitud                Int64
tmed                 Float64
prec                 Float64
tmin                 Float64
tmax                 Float64
velmedia             Float64
sol                  Float64
presMax              Float64
presMin              Float64
hrMedia              Float64
dir                  Float64
racha                Float64
hrMax                Float64
hrMin                Float64
lon                  Float64
lat                  Float64
dtype: object

### Reestructuración en formato tidy data

In [5]:
# Columna con las fechas
COL_FECHA = 'fecha'

# Columnas con la ubicación de cada medición
cols_localizacion = [
    'nombre',
    'provincia',
]
# Columnas con las variables que usaremos en la visualización
cols_variables = [
    'tmax',
    'tmed',
    'tmin',
    'sol',
    'racha',
    'velmedia',
    'hrMax',
    'hrMedia',
    'hrMin',
    'prec'
]

# Nombres de las columnas a añadir
COL_VAR = 'variable'
COL_VAL = 'valor'

In [6]:
df_tidy = df.copy(deep = True)

In [7]:
# Despivotamos las columnas con las variables, convirtiéndolas en pares variable - valor
df_tidy = df_tidy.melt(
    id_vars = [COL_FECHA] + cols_localizacion,
    value_vars = cols_variables,
    var_name = COL_VAR,
    value_name = COL_VAL
)

In [8]:
# Limpiamos todas aquellas que no tengan valor
df_tidy = df_tidy.dropna(subset=[COL_VAL])

In [9]:
display(df_tidy.sample(20))

,fecha,nombre,provincia,variable,valor
51667894,2024-01-23,"PANTICOSA, PETROSOS",HUESCA,hrMax,83.0
46965048,2007-04-24,CAMPDEVANOL,GIRONA,hrMax,92.0
40341359,2011-03-30,"LOS TOJOS, BÁRCENA MAYOR",CANTABRIA,velmedia,0.6
22860472,1983-04-26,SAN JAVIER AEROPUERTO,MURCIA,sol,8.0
14028402,2022-06-12,AMURRIO,ARABA/ALAVA,tmed,23.3
55314022,2011-09-12,BOADILLA FUENTE SAN ESTEBAN,SALAMANCA,hrMedia,53.0
64110275,2016-05-23,ARCHENA,MURCIA,hrMin,27.0
33703144,2014-01-17,"SAN ANDRÉS, VALVERDE",SANTA CRUZ DE TENERIFE,racha,20.3
34633014,2017-02-10,JALANCE,VALENCIA,racha,7.8
64961040,2019-02-21,SAN PABLO DE LOS MONTES,TOLEDO,hrMin,23.0
34925269,2018-01-20,COLL DE NARGÓ,LLEIDA,racha,13.3
66665746,2024-07-09,VÉLEZ BLANCO - TOPARES,ALMERIA,hrMin,28.0
65721163,2021-07-27,"BIESCAS, EMBALSE DE BÚBAL",HUESCA,hrMin,41.0
7492315,1971-10-26,GRAN CANARIA AEROPUERTO,LAS PALMAS,tmed,24.7
37218387,1972-07-13,TENERIFE NORTE AEROPUERTO,SANTA CRUZ DE TENERIFE,velmedia,3.1
55375714,2011-12-04,VALSEQUILLO,CORDOBA,hrMedia,77.0
3641101,2012-10-11,TÍAS,LAS PALMAS,tmax,24.6
21266548,2021-11-10,MADRID AEROPUERTO,MADRID,tmin,0.3
17552077,2009-03-09,SEGORBE,CASTELLON,tmin,5.9
56027868,2014-03-22,FUENCALIENTE,CIUDAD REAL,hrMedia,82.0

In [10]:
df_tidy.to_csv('Valores_Climatologicos_1970_2024_Tidy_Lite.csv', sep = ';', index = False)