In [1]:
import pandas as pd
import numpy as np

from loader import cargar_dataset

In [2]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024_con_Coordenadas.csv'

In [3]:
df = cargar_dataset(url = PATH_VAL_CLIM, variables_brutas = True)

In [4]:
display(df.sample(20))

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,presMax,presMin,hrMedia,dir,racha,hrMax,hrMin,lon,lat
5883106,2020-02-25,C649R,"TELDE, MELENARA",LAS PALMAS,9,"21,6","0,0","15,6","27,6","2,5",NaN,NaN,NaN,48.0,35.0,"10,0",71.0,18.0,-15.377778,27.986667
2531433,2008-02-20,1387,A CORUÑA,A CORUÑA,57,"16,1","0,0","13,0","19,2","2,5","3,6","1015,1","1008,3",77.0,16.0,"7,5",NaN,NaN,-8.421389,43.365833
5590753,2019-03-20,5860E,"MOGUER, EL ARENOSILLO",HUELVA,41,"14,2","0,0","8,1","20,2","3,6",NaN,NaN,NaN,53.0,99.0,"7,8",70.0,36.0,-6.738056,37.098056
345572,1978-02-10,1521I,O PÁRAMO,LUGO,403,NaN,"0,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.499444,42.845278
2798963,2009-08-09,6058I,ESTEPONA,MALAGA,19,"24,3","0,0","17,0","31,6","1,1",NaN,"1012,5","1009,8",58.0,18.0,"7,5",82.0,27.0,-5.155,36.416944
3671836,2012-11-16,1012P,IRUN,GIPUZKOA,120,"17,7","0,0","13,8","21,6","0,6",NaN,NaN,NaN,62.0,18.0,"6,9",78.0,51.0,-1.796667,43.326389
7014718,2023-09-22,1012P,IRUN,GIPUZKOA,120,"15,8","11,4","14,1","17,5","2,8",NaN,NaN,NaN,79.0,28.0,"10,8",92.0,62.0,-1.796667,43.326389
1767276,2001-08-10,1658,FOLGOSO DO COUREL,LUGO,612,NaN,"0,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.191667,42.588611
3991730,2013-12-28,1041A,ZUMAIA,GIPUZKOA,28,"10,8","4,6","8,5","13,0","2,2",NaN,NaN,NaN,62.0,31.0,"19,7",95.0,48.0,-2.251111,43.302222
1621944,1999-10-31,8293X,XÀTIVA,VALENCIA,88,"19,8","0,0","11,4","28,1","0,8",NaN,NaN,NaN,NaN,24.0,"5,3",NaN,NaN,-0.523056,39.001667
911095,1989-08-11,7031,SAN JAVIER AEROPUERTO,MURCIA,4,"26,4","0,0","22,5","30,4","3,6","9,1","1014,4","1012,0",74.0,8.0,"6,1",NaN,NaN,-0.803333,37.788889
4366416,2015-03-30,9436X,FONFRÍA,TERUEL,1255,"11,8","0,0","6,7","16,8","6,7",NaN,NaN,NaN,55.0,30.0,"16,9",84.0,39.0,-1.0875,40.995278
7039008,2023-10-19,5911A,GRAZALEMA,CADIZ,913,"12,9","109,0","10,1","15,7","2,8",NaN,"909,0","896,1",95.0,24.0,"16,4",98.0,88.0,-5.374167,36.760556
1102509,1992-10-01,1234P,"MIERES, BAIÑA",ASTURIAS,170,NaN,"0,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.819167,43.275
4020901,2014-02-03,2568D,"SANTERVÁS DE LA VEGA, VILLAPÚN",PALENCIA,985,"1,2",NaN,"-1,3","3,7","4,4",NaN,NaN,NaN,92.0,28.0,"13,9",100.0,67.0,-4.851111,42.523611
3935131,2013-10-18,9689X,TORRE DE CABDELLA,LLEIDA,1273,"15,8","0,0","9,9","21,7",NaN,NaN,NaN,NaN,65.0,NaN,NaN,94.0,43.0,0.990833,42.466389
3827383,2013-06-03,8414A,VALENCIA AEROPUERTO,VALENCIA,56,"19,3","0,0","13,8","24,8","3,9","13,2","1011,4","1008,0",48.0,99.0,"9,7",76.0,28.0,-0.474722,39.485
5039231,2017-06-09,3104Y,RASCAFRÍA,MADRID,1159,"19,0","0,0","10,2","27,7","0,8",NaN,NaN,NaN,42.0,29.0,"4,2",83.0,28.0,-3.888333,40.889722
1269571,1995-03-01,3365A,TALAVERA DE LA REINA,TOLEDO,372,"6,4","0,0","-1,9","14,7",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.863611,39.958611
5807639,2019-11-29,3111D,SOMOSIERRA,MADRID,1450,"7,0","17,4","5,2","8,8","0,3",NaN,NaN,NaN,96.0,88.0,"10,3",99.0,86.0,-3.580556,41.135556

### Preprocesado del Dataframe

In [5]:
df_prep = df.copy(deep = True)

In [6]:
COLS_VARIABLES = [
    'tmed',
    'prec',
    'tmin',
    'tmax',
    'velmedia',
    'sol',
    'presMax',
    'presMin',
    'hrMedia',
    'dir',
    'racha',
    'hrMax',
    'hrMin'
]

COL_PREC = 'prec'
COL_PROVINCIA = 'provincia'
COL_INDICATIVO = 'indicativo'
COL_TMAX = 'tmax'
COL_TMIN = 'tmin'
COL_DIR = 'dir'
COL_FECHA = 'fecha'

In [7]:
# Eliminamos las filas de precipitación acumulada, y cambiamos los valores 'Ip' por 0 (Ip = inferior a 0,1 mm)
df_prep = df_prep[df_prep[COL_PREC] != 'Acum']
df_prep[COL_PREC] = df_prep[COL_PREC].replace('Ip', 0)

In [8]:
# Reemplazamos las comas por puntos para poder cargar los números como decimales (floats)
df_prep[COLS_VARIABLES] = df_prep[COLS_VARIABLES].replace(',', '.', regex=True).apply(pd.to_numeric, errors = 'raise')

In [9]:
df_prep.dtypes

fecha         datetime64[ns]
indicativo    string[python]
nombre        string[python]
provincia     string[python]
altitud                Int64
tmed                 float64
prec                 float64
tmin                 float64
tmax                 float64
velmedia             float64
sol                  float64
presMax              float64
presMin              float64
hrMedia              float64
dir                  float64
racha                float64
hrMax                float64
hrMin                float64
lon                  Float64
lat                  Float64
dtype: object

In [10]:
# Corregimos inconsistencias en nombres de provincias
df_prep.loc[df_prep[COL_PROVINCIA] == 'BALEARES', COL_PROVINCIA] = 'ILLES BALEARS'
df_prep.loc[df_prep[COL_PROVINCIA] == 'STA. CRUZ DE TENERIFE', COL_PROVINCIA] = 'SANTA CRUZ DE TENERIFE'

In [11]:
# Borramos dos datos de una medición anómala
df_prep.loc[
    (df_prep[COL_INDICATIVO] == '6084X') &
    (df_prep[COL_TMIN] == 50.0) &
    (df_prep[COL_TMAX] == -50.0),
    [COL_TMIN, COL_TMAX]
] = np.nan

In [12]:
# Dejamos a NaN aquellos valores desconocidos (88: 'Desconocida') o múltiples (99: 'Varias), según el fichero de metadatos
df[COL_DIR] = df[COL_DIR].replace([99, 88], np.nan)

In [13]:
df_prep.sample(20)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,presMax,presMin,hrMedia,dir,racha,hrMax,hrMin,lon,lat
2692648,2009-02-13,7080X,MORATALLA,MURCIA,955,7.4,0.0,1.6,13.3,NaN,NaN,NaN,NaN,47.0,NaN,NaN,83.0,34.0,-1.986389,38.268333
3969720,2013-11-30,3514B,TORNAVACAS,CACERES,991,5.4,0.0,1.8,8.9,6.4,NaN,NaN,NaN,54.0,7.0,21.1,73.0,22.0,-5.678333,40.258611
3046990,2010-07-31,4478X,BADAJOZ,BADAJOZ,174,29.2,0.0,20.4,38.1,2.5,NaN,NaN,NaN,40.0,24.0,8.3,76.0,18.0,-7.009444,38.886111
221322,1975-06-06,8175,ALBACETE BASE AÉREA,ALBACETE,702,17.7,0.0,10.0,25.4,3.3,4.5,938.9,937.7,54.0,NaN,NaN,NaN,NaN,-1.856389,38.954167
4516051,2015-09-25,1435C,NOIA,A CORUÑA,128,20.0,0.0,14.9,25.0,NaN,NaN,NaN,NaN,79.0,NaN,NaN,96.0,63.0,-8.876111,42.800278
7415341,2024-12-18,3260B,TOLEDO,TOLEDO,513,7.2,0.0,0.1,14.3,0.8,6.0,972.0,966.4,72.0,11.0,3.9,96.0,49.0,-4.045278,39.884722
3763697,2013-03-14,9898,"HUESCA, AEROPUERTO",HUESCA,546,4.6,0.0,-0.2,9.4,12.2,10.7,948.2,942.6,54.0,30.0,23.3,65.0,44.0,-0.325556,42.084444
45105,1971-03-20,1159,SAN VICENTE DE LA BARQUERA,CANTABRIA,38,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.392222,43.393333
3779207,2013-04-03,8300X,CARCAIXENT,VALENCIA,25,14.2,0.2,6.7,21.7,3.3,NaN,NaN,NaN,61.0,14.0,11.1,89.0,37.0,-0.445833,39.113333
6736698,2022-11-08,1484C,PONTEVEDRA,PONTEVEDRA,113,15.2,17.4,12.9,17.6,2.5,0.0,1001.4,996.1,88.0,19.0,12.2,99.0,80.0,-8.615833,42.438333
1673835,2000-06-30,6155A,MÁLAGA AEROPUERTO,MALAGA,7,23.2,0.0,20.0,26.4,4.2,12.1,1015.4,1011.7,76.0,15.0,9.7,NaN,NaN,-4.482222,36.666111
2927258,2010-02-11,8175,ALBACETE BASE AÉREA,ALBACETE,702,1.9,0.0,-1.6,5.4,7.8,9.8,930.8,923.8,42.0,30.0,16.4,NaN,NaN,-1.856389,38.954167
5839289,2020-01-05,2517A,FUENTE EL SOL,VALLADOLID,755,-0.6,0.2,-1.8,0.7,0.6,NaN,NaN,NaN,100.0,29.0,2.8,100.0,99.0,-4.939722,41.172778
3255152,2011-05-14,9729X,MOLLERUSSA,LLEIDA,252,20.6,0.0,12.5,28.8,2.2,NaN,NaN,NaN,61.0,26.0,11.7,93.0,40.0,0.866667,41.616944
2392306,2007-02-08,1505,LUGO AEROPUERTO,LUGO,442,10.6,8.0,7.6,13.6,2.2,2.9,954.5,947.3,70.0,20.0,14.7,94.0,48.0,-7.4575,43.111111
1767235,2001-08-10,1735X,XINZO DE LIMIA,OURENSE,616,17.8,0.0,7.8,27.7,1.7,NaN,948.9,946.2,63.0,35.0,7.2,99.0,41.0,-7.733611,42.079167
1660396,2000-04-28,1014,"HONDARRIBIA, MALKARROA",GIPUZKOA,4,11.9,0.3,7.7,16.1,1.9,7.2,1013.7,1011.4,75.0,28.0,7.5,NaN,NaN,-1.792222,43.356944
6442579,2021-12-06,9908X,LANAJA,HUESCA,380,7.6,0.0,3.6,11.5,10.6,NaN,NaN,NaN,72.0,30.0,19.4,83.0,66.0,-0.333056,41.773889
1309455,1995-09-21,2331,BURGOS AEROPUERTO,BURGOS,891,12.2,0.0,6.4,18.0,4.7,9.1,919.9,917.1,73.0,9.0,11.7,NaN,NaN,-3.620278,42.356944
1829597,2002-04-22,0411X,CASTELLÓ D'EMPÚRIES,GIRONA,2,13.2,0.0,6.5,20.0,1.7,NaN,NaN,NaN,NaN,14.0,7.8,NaN,NaN,3.093056,42.224722

In [14]:
display(df_prep.describe().style.format({col: "{:.2f}" for col in df_prep.columns if col != COL_FECHA})) # Formateamos todo con 2 decimales excepto la fecha

In [15]:
df_prep.to_csv('Valores_Climatologicos_1970_2024_Limpios.csv', sep = ';', index = False)