In [1]:
import pandas as pd
import numpy as np

from loader import cargar_dataset_limpio

### Carga del Dataset

In [2]:
df = cargar_dataset_limpio()

In [2]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024_Limpios.csv'

In [3]:
COLS_NOMBRES = [
    'indicativo',
    'nombre',
    'provincia',
]

COLS_INTS = [
    'altitud'
]

COLS_FLOATS = [
    'tmed',
    'prec',
    'tmin',
    'tmax',
    'velmedia',
    'sol',
    'presMax',
    'presMin',
    'hrMedia',
    'dir',
    'racha',
    'hrMax',
    'hrMin'
]

COLS_NUMS = COLS_INTS + COLS_FLOATS

COL_FECHA = 'fecha'
COLS_HORAS = [
    'horaPresMax',
    'horaPresMin',
    'horatmin',
    'horatmax',
    'horaracha',
    'horaHrMax',
    'horaHrMin'
]

COLS_COORDS = [
    'lat',
    'lon'
]

In [5]:
dict_test = {
    'abc': 'def',
 '123': '456'
}

In [6]:
dict_test.keys()

dict_keys(['abc', '123'])

In [7]:
list_test = ['abc', '123', 'qwerty']

In [8]:
keys_que_faltan = list(set(list_test) - set(dict_test.keys()))

In [9]:
keys_que_faltan

['qwerty']

In [10]:
dict_test = dict_test | {key: 'asdf' for key in keys_que_faltan}

In [11]:
dict_test.keys()

dict_keys(['abc', '123', 'qwerty'])

In [12]:
df = pd.read_csv(PATH_VAL_CLIM,
                 sep=';', decimal = ',',
                 dtype = {nombre: 'string' for nombre in COLS_NOMBRES} |
                         {entero: 'Int64' for entero in COLS_INTS} |
                         {coordenada: 'Float64' for coordenada in COLS_COORDS} |
                         {otros: 'object' for otros in COLS_FLOATS + COLS_HORAS},
                         # {decimal: 'Float64' for decimal in COLS_FLOATS if decimal != 'prec'},
                 parse_dates = [COL_FECHA])

In [13]:
display(df)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin,lon,lat,dir_tipo
0,1970-01-01,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,19.8,0.0,16.0,23.5,6.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.863056,28.444722,Válida
1,1970-01-01,1679A,MONFORTE DE LEMOS,LUGO,291,4.0,0.0,0.0,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7.510833,42.531667,Válida
2,1970-01-01,2462,PUERTO DE NAVACERRADA,MADRID,1893,-5.0,0.4,-7.0,-3.0,3.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.010556,40.793056,Válida
3,1970-01-01,1212E,ASTURIAS AEROPUERTO,ASTURIAS,127,4.3,2.6,2.0,6.6,0.0,...,99.0,7.2,00:13,NaN,NaN,NaN,NaN,-6.044167,43.566944,Varias
4,1970-01-01,0016A,REUS AEROPUERTO,TARRAGONA,71,5.5,0.0,0.6,10.4,1.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.163611,41.145,Válida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7424496,2024-12-31,9562X,MORELLA,CASTELLON,990,4.8,0.0,0.8,8.8,1.4,...,12.0,5.0,16:50,97.0,23:50,63.0,14:00,-0.101944,40.621667,Válida
7424497,2024-12-31,1002Y,"BAZTAN, IRURITA",NAVARRA,183,4.2,0.0,-4.9,13.4,0.0,...,22.0,3.1,16:20,100.0,09:00,50.0,14:10,-1.543056,43.135833,Válida
7424498,2024-12-31,3254Y,MORA,TOLEDO,717,2.0,0.0,-3.1,7.1,1.1,...,20.0,3.9,14:30,100.0,09:20,80.0,11:20,-3.780556,39.686944,Válida
7424499,2024-12-31,0194D,"CORBERA, PUIG D'AGULLES",BARCELONA,647,NaN,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.885,41.408056,Válida
7424500,2024-12-31,4093Y,OSA DE LA VEGA,CUENCA,763,4.1,0.0,-1.8,10.0,1.4,...,99.0,6.1,Varias,97.0,09:00,62.0,15:50,-2.76,39.656111,Varias

In [14]:
df_test = pd.read_csv(PATH_VAL_CLIM, sep = ';', dtype = {'altud': 'Int64'}, nrows = 0)
df_test.columns

Index(['fecha', 'indicativo', 'nombre', 'provincia', 'altitud', 'tmed', 'prec',
       'tmin', 'tmax', 'velmedia', 'sol', 'presMax', 'horaPresMax', 'presMin',
       'horaPresMin', 'hrMedia', 'horatmin', 'horatmax', 'dir', 'racha',
       'horaracha', 'hrMax', 'horaHrMax', 'hrMin', 'horaHrMin', 'lon', 'lat',
       'dir_tipo'],
      dtype='object')

In [15]:
for col in df_test.columns:
    print(col)

fecha
indicativo
nombre
provincia
altitud
tmed
prec
tmin
tmax
velmedia
sol
presMax
horaPresMax
presMin
horaPresMin
hrMedia
horatmin
horatmax
dir
racha
horaracha
hrMax
horaHrMax
hrMin
horaHrMin
lon
lat
dir_tipo

In [16]:
df_test.dtypes

fecha          object
indicativo     object
nombre         object
provincia      object
altitud        object
tmed           object
prec           object
tmin           object
tmax           object
velmedia       object
sol            object
presMax        object
horaPresMax    object
presMin        object
horaPresMin    object
hrMedia        object
horatmin       object
horatmax       object
dir            object
racha          object
horaracha      object
hrMax          object
horaHrMax      object
hrMin          object
horaHrMin      object
lon            object
lat            object
dir_tipo       object
dtype: object

### Preprocesado del Dataframe

In [17]:
df_prep = df.copy(deep = True)

In [18]:
COL_PREC = 'prec'
# df_prep.loc[df[COL_PREC] == 'Ip', COL_PREC] = 0
df_prep = df_prep[df_prep[COL_PREC] != 'Acum']
df_prep[COL_PREC] = df_prep[COL_PREC].replace('Ip', 0)

In [19]:
# Reemplazamos las comas por puntos para poder cargar los números como decimales (floats)
df_prep[COLS_FLOATS] = df_prep[COLS_FLOATS].replace(',', '.', regex=True).apply(pd.to_numeric, errors = 'raise')

In [20]:
df_prep.dtypes

fecha          datetime64[ns]
indicativo     string[python]
nombre         string[python]
provincia      string[python]
altitud                 Int64
tmed                  float64
prec                  float64
tmin                  float64
tmax                  float64
velmedia              float64
sol                   float64
presMax               float64
horaPresMax            object
presMin               float64
horaPresMin            object
hrMedia               float64
horatmin               object
horatmax               object
dir                   float64
racha                 float64
horaracha              object
hrMax                 float64
horaHrMax              object
hrMin                 float64
horaHrMin              object
lon                   Float64
lat                   Float64
dir_tipo               object
dtype: object

In [21]:
# Corregimos inconsistencias en nombres de provincias
df_prep.loc[df_prep['provincia'] == 'BALEARES', 'provincia'] = 'ILLES BALEARS'
df_prep.loc[df_prep['provincia'] == 'SANTA CRUZ DE TENERIFE', 'provincia'] = 'STA. CRUZ DE TENERIFE'

In [22]:
# Borramos dos datos de una medición anómala
df_prep.loc[
    (df_prep['indicativo'] == '6084X') &
    (df_prep['tmin'] == 50.0) &
    (df_prep['tmax'] == -50.0),
    ['tmax', 'tmin']
] = np.nan

In [23]:
# Procesamos dirección del viento (según la info proporcionada en el fichero de metadatos)
dict_dir = {
    88: 'Desconocida',
    99: 'Varias'
}
dir_por_defecto = 'Válida'

df_prep['dir_tipo'] = df_prep['dir'].map(dict_dir).fillna(dir_por_defecto)

In [24]:
# Añadimos el sufijo :00 a las columnas cuyos valores carecen de él
cols_sufijo = ['horaPresMax', 'horaPresMin']
df_prep[cols_sufijo] = df_prep[cols_sufijo].where(
    df_prep[cols_sufijo].isna() | (df_prep[cols_sufijo] == 'Varias'),
    df_prep[cols_sufijo] + ':00'
)

### Reestructuración en formato tidy data

In [25]:
# Columnas asociadas a la estación de medición
cols_estacion = [
    'indicativo',
    'nombre',
    'provincia',
    'altitud',
    'lon',
    'lat'
]
# Pares variable - hora
dict_horas = {
    "tmin": "horatmin",
    "tmax": "horatmax",
    "presMax": "horaPresMax",
    "presMin": "horaPresMin",
    "racha": "horaracha",
    "hrMax": "horaHrMax",
    "hrMin": "horaHrMin"
}

# Variables sin hora asociada
cols_var_sin_horas = [
    "tmed",
    "prec",
    "velmedia",
    "sol",
    "hrMedia",
    "dir"
]

In [26]:
# Despivotamos las columnas sin hora, añadimos columna 'hora' y la llenamos de NAs
df_sin_horas = df_prep.melt(
    id_vars = [COL_FECHA] + cols_estacion,
    value_vars = cols_var_sin_horas,
    var_name = 'variable',
    value_name = 'valor'
)

df_sin_horas['hora'] = pd.Series([pd.NaT] * len(df_sin_horas), dtype = 'datetime64[ns]').dt.time

# df_sin_horas['hora'] = pd.NA
df_sin_horas['tipo_hora'] = pd.NA

# Pasamos a time para que los deje como NaT y ser consistente con las horas cuando se concatene
# df_sin_horas['hora'] = pd.to_datetime(df_sin_horas['hora'], format = '%H:%M', errors = 'coerce').dt.time

In [27]:
# Despivotamos las columnas con hora, y rellenamos la columna 'hora' con el valor de la columna 'horaVAR' original
lista_dfs_temp = []
for variable, col_hora in dict_horas.items():
    df_temp = df_prep[[COL_FECHA] + cols_estacion + [variable, col_hora]].rename(columns = {variable: 'valor', col_hora: 'hora'})
    df_temp['variable'] = variable
    lista_dfs_temp.append(df_temp)

df_con_horas = pd.concat(lista_dfs_temp, ignore_index=True)

In [28]:
# Procesamiento de horas
COL_HORA = 'hora'
COL_TIPO = 'tipo_hora'
CATEGORIAS = ['Desconocida',
              'Varias',
              'Válida',
              'Inválida'] # Valor por defecto si no cuadra en ninguna de las demás

filtro_formato = df_con_horas[COL_HORA].str.match(r'^\d{1,2}:\d{2}$', na=False) # Comprueba que formato HH:MM
df_hhmm = df_con_horas.loc[filtro_formato, COL_HORA].str.split(":", expand=True).astype(int) # Df con dos columnas: HH y MM
filtro_rango = (df_hhmm[0].between(0, 23)) & (df_hhmm[1].between(0, 59)) # Comprueba HH entre 0-23; MM entre 0-59 
filtro_hhmm = filtro_rango.reindex(df_con_horas.index, fill_value = False) # Para mismo tamaño que original

# Anotamos anomalías en la hora
filtros = [
    df_con_horas[COL_HORA].isna(),
    df_con_horas[COL_HORA] == 'Varias',
    filtro_hhmm
]

df_con_horas[COL_TIPO] = np.select(filtros, CATEGORIAS[:-1], default = CATEGORIAS[-1])
df_con_horas[COL_TIPO] = df_con_horas[COL_TIPO].astype('category')

# Pasamos las horas a tipo time
df_con_horas[COL_HORA] = pd.to_datetime(
    df_con_horas[COL_HORA], format = '%H:%M', errors = 'coerce'
).dt.time

# Creamos columna datetime respectiva
# df_prep['fecha' + col] = pd.to_datetime(
#     df_prep[COL_FECHA].dt.date.astype(str) + ' ' + df_prep[col].astype(str),
#     format = '%Y-%m-%d %H:%M',
#     errors = 'coerce'
# )

In [29]:
df_prep = pd.concat([df_sin_horas, df_con_horas], ignore_index=True)

C:\Users\Big Data\AppData\Local\Temp\ipykernel_34280\1695853820.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_prep = pd.concat([df_sin_horas, df_con_horas], ignore_index=True)

In [30]:
df_prep.sample(20)

,fecha,indicativo,nombre,provincia,altitud,lon,lat,variable,valor,hora,tipo_hora
82504159,1988-04-04,1109,SANTANDER AEROPUERTO,CANTABRIA,3,-3.825556,43.423889,hrMax,NaN,NaT,Desconocida
6502120,2022-02-15,9336D,CASTEJON DE VALDEJASA,ZARAGOZA,543,-0.995833,41.984167,tmed,7.2,NaN,NaN
30484359,1987-04-28,1234P,"MIERES, BAIÑA",ASTURIAS,170,-5.819167,43.275,hrMedia,NaN,NaN,NaN
87036238,2018-07-03,C457E,CITFAGRO_67_MATANZA,STA. CRUZ DE TENERIFE,650,-16.438056,28.449444,hrMax,99.0,NaT,Varias
45943247,1996-12-20,8500A,CASTELLÓ - ALMASSORA,CASTELLON,43,-0.071944,39.957222,tmin,7.6,04:30:00,Válida
8644661,1994-06-28,0341,TONA (ESCOLA),BARCELONA,611,2.226667,41.846667,prec,0.0,NaN,NaN
5381146,2018-07-21,C249I,FUERTEVENTURA AEROPUERTO,LAS PALMAS,25,-13.863056,28.444722,tmed,25.1,NaN,NaN
51161205,2022-06-24,3365A,TALAVERA DE LA REINA,TOLEDO,372,-4.863611,39.958611,tmin,10.6,05:00:00,Válida
67914231,1992-08-20,0016A,REUS AEROPUERTO,TARRAGONA,71,1.163611,41.145,presMin,1004.3,NaT,Inválida
2248774,2006-01-27,1428,SANTIAGO DE COMPOSTELA AEROPUERTO,A CORUÑA,370,-8.410556,42.888056,tmed,4.4,NaN,NaN
32677508,2010-04-30,2728B,"QUINTANA DEL CASTILLO, VILLAMECA",LEON,995,-6.070833,42.648333,hrMedia,66.0,NaN,NaN
84644070,2010-04-23,5941X,EL BOSQUE,CADIZ,295,-5.512222,36.729444,hrMax,95.0,01:10:00,Válida
11093315,2012-11-15,4386B,LLERENA,BADAJOZ,655,-6.016944,38.231667,prec,0.0,NaN,NaN
13760548,2021-08-09,1111,SANTANDER,CANTABRIA,52,-3.800556,43.491111,prec,0.0,NaN,NaN
87561214,2020-03-09,5919X,OLVERA,CADIZ,530,-5.259444,36.931667,hrMax,72.0,07:30:00,Válida
22602382,1977-10-05,C625O,"SAN BARTOLOME TIRAJANA, LOMO PEDRO ALFONSO",LAS PALMAS,806,-15.645,27.856944,sol,NaN,NaN,NaN
48675690,2014-06-19,4148,VISO DEL MARQUÉS,CIUDAD REAL,804,-3.566667,38.518056,tmin,18.0,04:00:00,Válida
73684116,2023-04-06,3337U,CEBREROS,AVILA,850,-4.455833,40.4675,presMin,NaN,NaT,Desconocida
208567,1975-02-24,C430E,IZAÑA,STA. CRUZ DE TENERIFE,2369,-16.499722,28.308333,tmed,7.8,NaN,NaN
53504020,1998-09-19,4452,BADAJOZ AEROPUERTO,BADAJOZ,186,-6.813889,38.883333,tmax,30.6,13:15:00,Válida

In [31]:
df_prep.to_csv('Valores_Climatologicos_1970_2024_Limpios.csv', sep = ';', index = False)

KeyboardInterrupt:

In [ ]:
df_sin_horas.sample(20)

In [ ]:
# De aquí para abajo es en sucio, ignorar

In [ ]:
raise Exception()

In [ ]:
# --- Clasificación de tipo_hora ---
filtro_formato = df["hora"].str.match(r'^\d{1,2}:\d{2}$', na=False)

# split HH:MM solo para las válidas
df_hhmm = df.loc[filtro_formato, "hora"].str.split(":", expand=True).astype(int)
filtro_rango = (df_hhmm[0].between(0, 23)) & (df_hhmm[1].between(0, 59))

# Alinear tamaños (True/False por fila del df original)
filtro_hhmm = filtro_rango.reindex(df.index, fill_value=False)

filtros = [
    df["hora"].isna(),
    df["hora"] == "Varias",
    filtro_hhmm
]

df["tipo_hora"] = np.select(filtros, CATEGORIAS[:-1], default=CATEGORIAS[-1])
df["tipo_hora"] = df["tipo_hora"].astype("category")

# --- Convertir a tipo time ---
df["hora"] = pd.to_datetime(
    df["hora"], format="%H:%M", errors="coerce"
).dt.time

# --- Crear fecha+hora ---
df["fechahora"] = pd.to_datetime(
    df["fecha"].dt.date.astype(str) + " " + df["hora"].astype(str),
    format="%Y-%m-%d %H:%M",
    errors="coerce"
)

In [ ]:
# Columnas asociadas a la estación de medición
cols_estacion = [
    'indicativo',
    'nombre',
    'provincia',
    'altitud',
    'lon',
    'lat'
]

# id_vars = ["fecha", "indicativo", "nombre", "provincia", "altitud", "lon", "lat"]

# Pares variable - hora
dict_horas = {
    "tmin": "horatmin",
    "tmax": "horatmax",
    "presMax": "horaPresMax",
    "presMin": "horaPresMin",
    "racha": "horaracha",
    "hrMax": "horaHrMax",
    "hrMin": "horaHrMin"
}

# Variables sin hora
cols = [
    "tmed", "prec", "velmedia", "sol", "hrMedia", "dir"
]

# --- 1) Melt para las que NO tienen hora ---
df_nohora = df.melt(
    id_vars=id_vars,
    value_vars=without_hour,
    var_name="variable",
    value_name="valor"
)
df_nohora["hora"] = pd.NA  # sin hora asociada

# --- 2) Melt para las que SÍ tienen hora ---
dfs = []
for var, hora_col in with_hour.items():
    tmp = df[id_vars + [var, hora_col]].rename(columns={var: "valor", hora_col: "hora"})
    tmp["variable"] = var
    dfs.append(tmp)

df_hora = pd.concat(dfs, ignore_index=True)

# --- 3) Unimos todo ---
df_tidy = pd.concat([df_nohora, df_hora], ignore_index=True)

# Opcional: ordenar
df_tidy = df_tidy.sort_values(["fecha", "provincia", "variable"]).reset_index(drop=True)

In [ ]:
cols_horas = [
    'horaPresMax',
    'horaPresMin',
    'horatmin',
    'horatmax',
    'horaracha',
    'horaHrMax',
    'horaHrMin'
]

df_prep[cols_horas].astype(str).values

# sorted(list(set(df_prep[cols_horas].astype(str).values)))[-5:]

lista_vals_horas = df_prep[cols_horas].astype(str).values

lista_vals_horas_flat = [val for sublista in lista_vals_horas for val in sublista]

In [ ]:
# Añadimos el sufijo :00 a las columnas cuyos valores carecen de él
cols_sufijo = ['horaPresMax', 'horaPresMin']
df_prep[cols_sufijo] = df_prep[cols_sufijo].where(
    df_prep[cols_sufijo].isna() | (df_prep[cols_sufijo] == 'Varias'),
    df_prep[cols_sufijo] + ':00'
)

In [ ]:
# Procesamiento de horas
CATEGORIAS = ['Desconocida',
              'Varias',
              'Válida',
              'Inválida'] # Valor por defecto si no cuadra en ninguna de las demás

for col in cols_horas:

    filtro_formato = df_prep[col].str.match(r'^\d{1,2}:\d{2}$', na=False) # Comprueba que formato HH:MM
    df_hhmm = df_prep.loc[filtro_formato, col].str.split(":", expand=True).astype(int) # Df con dos columnas: HH y MM
    filtro_rango = (df_hhmm[0].between(0, 23)) & (df_hhmm[1].between(0, 59)) # Comprueba HH entre 0-23; MM entre 0-59 
    filtro_hhmm = filtro_rango.reindex(df_prep.index, fill_value = False) # Para mismo tamaño que original
    
    # Anotamos anomalías en la hora
    filtros = [
        df_prep[col].isna(),
        df_prep[col] == 'Varias',
        filtro_hhmm
    ]

    df_prep[col + '_tipo'] = np.select(filtros, CATEGORIAS[:-1], default = CATEGORIAS[-1])
    df_prep[col + '_tipo'] = df_prep[col + '_tipo'].astype('category')

    # Pasamos las horas a tipo time
    df_prep[col] = pd.to_datetime(
        df_prep[col], format = '%H:%M', errors = 'coerce'
    ).dt.time

    # Creamos columna datetime respectiva
    df_prep['fecha' + col] = pd.to_datetime(
        df_prep[COL_FECHA].dt.date.astype(str) + ' ' + df_prep[col].astype(str),
        format = '%Y-%m-%d %H:%M',
        errors = 'coerce'
    )

In [ ]:
# Procesamos dirección del viento
dict_dir = {
    88: 'Desconocida',
    99: 'Varias'
}
dir_por_defecto = 'Válida'

df_prep['dir_tipo'] = df_prep['dir'].map(dict_dir).fillna(dir_por_defecto)

In [ ]:
df_prep.loc[df_prep['provincia'] == 'BALEARES', 'provincia'] = 'ILLES BALEARS'
df_prep.loc[df_prep['provincia'] == 'SANTA CRUZ DE TENERIFE', 'provincia'] = 'STA. CRUZ DE TENERIFE'

In [ ]:
df_prep.loc[
    (df_prep['indicativo'] == '6084X') &
    (df_prep['tmin'] == 50.0) &
    (df_prep['tmax'] == -50.0),
    ['tmax', 'tmin']
] = np.nan

In [ ]:
df_prep.to_csv('Valores_Climatologicos_1970_2024_Limpios.csv', sep = ';', index = False)