In [1]:
import pandas as pd

In [2]:
PATH_VAL_CLIM = 'Valores_Climatologicos_1970_2024.csv'

In [3]:
df = pd.read_csv(PATH_VAL_CLIM, sep=';', dtype=str)

In [4]:
display(df.sample(20))

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,hrMedia,horatmin,horatmax,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin
5034807,2017-06-04,B986,FORMENTERA,ILLES BALEARS,24,"21,2",NaN,"15,9","26,4","4,7",...,80.0,22:40,15:40,30.0,"20,0",22:10,95.0,22:50,74.0,15:30
2432896,2007-05-27,1437O,MONTE IROITE,A CORUÑA,685,"9,8",NaN,"6,4","13,3",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4907500,2017-01-05,2930Y,NAVASFRÍAS,SALAMANCA,880,"5,0","0,0","-1,6","11,5","0,8",...,88.0,21:59,14:42,36.0,"6,7",14:10,100.0,Varias,64.0,15:10
5939111,2020-04-30,4527X,AROCHE,HUELVA,267,"15,6","0,0","11,4","19,9","1,1",...,78.0,24:00,16:48,27.0,"6,1",11:00,99.0,05:50,61.0,Varias
2552098,2008-04-13,2804F,VILLADEPERA,ZAMORA,790,"7,4","2,8","3,4","11,5","7,5",...,88.0,02:17,15:46,NaN,NaN,NaN,99.0,Varias,67.0,15:50
3763586,2013-03-14,8008Y,VILLENA,ALICANTE,486,"6,9","0,0","1,3","12,5","8,6",...,44.0,05:08,15:16,31.0,"18,3",11:20,63.0,06:20,31.0,15:30
260444,1976-04-14,0002I,VANDELLÒS,TARRAGONA,32,"16,1","0,0","11,2","21,0","7,8",...,35.0,05:50,15:00,32.0,"23,3",22:42,NaN,NaN,NaN,NaN
6055870,2020-09-15,1521I,O PÁRAMO,LUGO,403,"21,1","0,0","13,4","28,8",NaN,...,67.0,06:51,14:24,NaN,NaN,NaN,99.0,Varias,40.0,14:10
6906915,2023-05-22,C611E,VEGA DE SAN MATEO,LAS PALMAS,1702,"7,2","0,2","4,0","10,4","1,7",...,86.0,07:04,15:25,9.0,"8,1",23:30,100.0,Varias,71.0,12:10
4788044,2016-08-15,1442U,BOIRO,A CORUÑA,10,"17,0","0,0","14,4","19,6",NaN,...,85.0,Varias,16:53,NaN,NaN,NaN,96.0,Varias,78.0,Varias
2532507,2008-02-23,1037X,LEGAZPI,GIPUZKOA,460,"11,6","0,2","4,7","18,5",NaN,...,NaN,06:30,14:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3220183,2011-03-28,C639M,"MASPALOMAS, C. INSULAR TURISMO",LAS PALMAS,45,"20,4","0,0","16,1","24,7","1,7",...,66.0,07:00,14:22,26.0,"8,9",14:50,78.0,07:00,47.0,14:30
3830933,2013-06-07,2491C,"LA COVATILLA, ESTACIÓN DE ESQUÍ",SALAMANCA,1960,"3,2","7,6","0,5","6,0",NaN,...,91.0,12:30,15:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
220942,1975-06-03,8501,CASTELLÓ DE LA PLANA,CASTELLON,23,"16,9","0,0","12,6","21,2","1,4",...,67.0,05:15,14:20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5877960,2020-02-19,2945A,EL BODÓN BASE AÉREA,SALAMANCA,805,"5,4","0,0","-2,6","13,3","1,1",...,68.0,07:38,15:27,36.0,"5,3",00:10,98.0,08:40,46.0,14:50
2754126,2009-05-31,4061X,QUINTANAR DE LA ORDEN,TOLEDO,692,NaN,"0,0",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5631593,2019-05-07,9911X,BALLOBAR,HUESCA,178,"16,6","0,0","7,2","25,9","2,8",...,60.0,Varias,15:29,9.0,"9,4",16:10,84.0,Varias,41.0,14:30
1184717,1993-12-21,C029O,LANZAROTE AEROPUERTO,LAS PALMAS,14,"17,2","0,0","13,3","21,1","6,4",...,72.0,07:10,13:10,7.0,"9,7",13:50,NaN,NaN,NaN,NaN
6388449,2021-10-05,C614H,TEJEDA,LAS PALMAS,1060,"19,0","0,0","12,8","25,3","2,5",...,55.0,04:50,13:40,9.0,"12,8",00:30,84.0,Varias,17.0,16:00
6083167,2020-10-17,9563X,CASTELLFORT,CASTELLON,1220,"8,5","0,0","3,5","13,5",NaN,...,46.0,00:50,13:10,NaN,NaN,NaN,81.0,00:50,31.0,13:00

In [5]:
PATH_ESTACIONES = 'Inventario_Estaciones_AEMET.csv'

In [6]:
df_estaciones = pd.read_csv(PATH_ESTACIONES, sep=';', dtype=str)

In [7]:
display(df_estaciones.sample(20))

,Unnamed: 0,latitud,provincia,altitud,indicativo,nombre,indsinop,longitud
199,199,421533N,GIRONA,45,0429X,FIGUERES,NaN,025737E
297,297,425317N,A CORUÑA,370,1428,SANTIAGO DE COMPOSTELA AEROPUERTO,08042,082438W
17,17,392024N,ILLES BALEARS,45,B410B,SANTANYÍ,NaN,030845E
105,105,282207N,STA. CRUZ DE TENERIFE,595,C458U,CITFAGRO_71_PALOB,NaN,163441W
93,93,282745N,STA. CRUZ DE TENERIFE,136,C448C,CITFAGRO_92_SANTACRUZ,NaN,161624W
868,868,413938N,ZARAGOZA,249,9434,"ZARAGOZA, AEROPUERTO",08160,010015W
351,351,414445N,BURGOS,955,2106B,CORUÑA DEL CONDE,NaN,032255W
811,811,424114N,BURGOS,460,9069C,MIRANDA DE EBRO,NaN,025738W
225,225,432230N,BIZKAIA,81,1059X,PUNTA GALEA,08059,030118W
228,228,430557N,BIZKAIA,747,1069Y,"ABADIÑO, URKIOLA",NaN,023839W
252,252,431521N,CANTABRIA,940,1176A,TRESVISO,NaN,044006W
81,81,281301N,STA. CRUZ DE TENERIFE,930,C426R,CITFAGRO_09_HELECHO,NaN,162926W
125,125,274845N,LAS PALMAS,41,C639U,"SAN BARTOLOME TIRAJANA, EL MATORRAL",NaN,152711W
360,360,425214N,PALENCIA,1140,2235U,CERVERA DE PISUERGA,08058,043112W
915,915,412449N,LLEIDA,392,9775X,EL SOLERÀS,NaN,004042E
380,380,410417N,AVILA,820,2456B,AREVALO,NaN,044348W
641,641,365919N,HUELVA,5,5858X,ALMONTE,NaN,062635W
874,874,423046N,HUESCA,775,9460X,SABIÑÁNIGO,NaN,002120W
412,412,420039N,ZAMORA,715,2755X,BENAVENTE,08056,054000W
935,935,405224N,TERUEL,483,9935X,VALDERROBRES,NaN,000847E

In [8]:
def procesar_coordenada(coord_str: str) -> float:
    """
    Convierte coordenadas en formato DMS compacto a formato decimal (float).
    """

    direccion = coord_str[-1] # Último carácter, la letra (N, S, E, W)
    coord = coord_str[:-1] # Todos los demás dígitos

    # Formato DMS: DDMMSS / DDDMMSS
    grados = int(coord[:-4])    # Los primeros N - 4 dígitos (DD o DDD)
    minutos = int(coord[-4:-2]) # Tercer y cuarto dígitos empezando por el final (MM)
    segundos = int(coord[-2:])  # Últimos dos dígitos (SS)

    coord_float = grados + minutos / 60 + segundos / 3600

    # Sur y oeste se codifican como negativos
    if direccion == 'S' or direccion == 'W':
        coord_float = -coord_float

    return coord_float

In [10]:
LON = 'lon'
LAT = 'lat'

In [11]:
df_estaciones[LON] = df_estaciones['longitud'].apply(procesar_coordenada)
df_estaciones[LAT] = df_estaciones['latitud'].apply(procesar_coordenada)

In [12]:
col_join = 'indicativo'

cols_coords = [
    LON,
    LAT
]

df_merged = df.merge(
    df_estaciones[[col_join] + cols_coords],
    on = col_join,
    how="left"
)

In [13]:
display(df_merged.sample(20))

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,...,horatmax,dir,racha,horaracha,hrMax,horaHrMax,hrMin,horaHrMin,lon,lat
4031160,2014-02-16,9981A,ESTACIÓN DE TORTOSA (ROQUETES),TARRAGONA,50,"7,6","2,2","4,6","10,7","2,2",...,15:00,2.0,"9,4",04:30,99.0,Varias,71.0,04:20,0.493333,40.820278
4226841,2014-10-13,2811A,NAVARREDONDA DE GREDOS,AVILA,1525,"7,6","2,9","3,7","11,6","1,1",...,09:50,17.0,"9,7",17:40,98.0,Varias,71.0,14:30,-5.143056,40.350556
4389611,2015-04-27,2512Y,RIVILLA DE BARAJAS,AVILA,925,"10,2","0,2","5,9","14,6","5,0",...,16:04,28.0,"10,8",13:10,98.0,Varias,55.0,16:20,-5.018611,40.882222
784076,1987-04-08,0016A,REUS AEROPUERTO,TARRAGONA,71,"17,7","0,0","13,0","22,4","2,5",...,13:00,22.0,"10,6",13:30,NaN,NaN,NaN,NaN,1.163611,41.145000
4772009,2016-07-27,2728B,"QUINTANA DEL CASTILLO, VILLAMECA",LEON,995,"22,2","0,0","13,0","31,4","2,8",...,15:19,99.0,"7,5",16:40,86.0,04:50,28.0,12:00,-6.070833,42.648333
385892,1978-12-17,1387E,A CORUÑA AEROPUERTO,A CORUÑA,98,"7,7","1,8","6,4","9,0","0,8",...,16:00,36.0,"11,4",04:00,NaN,NaN,NaN,NaN,-8.371944,43.306944
5854134,2020-01-22,2604B,MEDINA DE RIOSECO,VALLADOLID,731,"6,1","0,0","2,5","9,7","4,7",...,14:29,7.0,"14,7",01:00,90.0,Varias,63.0,Varias,-5.040278,41.875833
661309,1984-11-04,9434,"ZARAGOZA, AEROPUERTO",ZARAGOZA,249,"9,5","6,8","4,6","14,4","3,6",...,13:15,7.0,"8,1",10:16,NaN,NaN,NaN,NaN,-1.004167,41.660556
784027,1987-04-07,0076,BARCELONA AEROPUERTO,BARCELONA,4,"12,6","0,0","8,2","17,0","3,3",...,12:30,27.0,"8,9",Varias,NaN,NaN,NaN,NaN,2.070000,41.292778
1882182,2002-11-16,B434X,PORTOCOLOM,ILLES BALEARS,17,"15,2","9,2","12,9","17,5","3,3",...,12:00,25.0,"10,8",15:10,NaN,NaN,NaN,NaN,3.271667,39.414444
2161153,2005-05-21,7012C,CARTAGENA,MURCIA,17,"20,4","0,0","17,1","23,8","1,1",...,18:00,23.0,"6,7",09:10,92.0,23:40,55.0,07:20,-0.987778,37.601111
2145163,2005-04-05,1174I,"CILLÓRIGO DE LIÉBANA, TAMA",CANTABRIA,250,"15,0","0,0","10,0","20,0",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.601667,43.182778
4011256,2014-01-22,4589X,"ALOSNO, THARSIS",HUELVA,276,"10,6","1,0","6,6","14,5","2,8",...,15:34,34.0,"13,6",16:10,98.0,Varias,71.0,14:10,-7.119444,37.597778
609437,1983-10-11,0367,GIRONA AEROPUERTO,GIRONA,143,"20,1","0,0","16,4","23,8","1,9",...,13:45,9.0,"8,1",14:50,NaN,NaN,NaN,NaN,2.763333,41.911667
176529,1974-06-10,1740,"SANTILLANA DEL MAR, ALTAMIRA",CANTABRIA,150,NaN,"6,5",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.124444,43.377222
5800577,2019-11-21,7012D,CARTAGENA,MURCIA,56,"12,2","0,0","7,8","16,5","1,9",...,11:30,20.0,"11,4",19:30,100.0,04:00,58.0,11:20,-1.023333,37.604444
61563,1971-08-27,2465A,"SEGOVIA, INSTITUTO",SEGOVIA,990,"17,6","0,0","9,8","25,4","1,1",...,17:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-4.115833,40.946667
6251481,2021-04-29,1199X,"PILOÑA, BARGAÉU",ASTURIAS,280,"9,7","4,4","8,1","11,3","1,1",...,10:19,7.0,"7,2",12:50,96.0,Varias,69.0,10:30,-5.396667,43.377778
1763978,2001-07-27,1549,PONFERRADA,LEON,532,"21,8","0,0","14,0","29,5","1,7",...,16:05,24.0,"8,9",17:28,NaN,NaN,NaN,NaN,-6.600000,42.563889
6983955,2023-08-18,0360X,LES PLANES D'HOSTOLES,GIRONA,337,"23,4","0,0","13,1","33,6","0,6",...,14:06,13.0,"6,7",14:30,94.0,23:50,41.0,11:50,2.551111,42.052778

In [14]:
df_merged.to_csv('Valores_Climatologicos_1970_2024_con_Coordenadas.csv', sep = ';', index = False)