In [1]:
import pandas as pd
import numpy as np

import constantes as const
from loader import cargar_dataset

In [3]:
df = cargar_dataset(url = const.PATH_DF_BRUTO, variables_brutas = True)

In [4]:
display(df.sample(20))

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,presMax,presMin,hrMedia,dir,racha,hrMax,hrMin,lon,lat
1230219,1994-08-11,2630X,PUERTO DE SAN ISIDRO,LEON,1510,"10,0","0,0","5,5","14,6","2,8",NaN,NaN,NaN,82.0,26.0,"9,2",98.0,62.0,-5.376944,43.062222
470627,1980-10-11,9263D,"PAMPLONA, AEROPUERTO",NAVARRA,459,"10,0","25,4","7,0","13,0","9,2","5,1","957,9","950,5",83.0,NaN,NaN,NaN,NaN,-1.65,42.776944
6332467,2021-08-01,4395X,VILLAFRANCA DE LOS BARROS,BADAJOZ,430,"20,4","0,0","13,2","27,6","4,4",NaN,NaN,NaN,45.0,31.0,"13,9",76.0,30.0,-6.306667,38.551667
1820122,2002-03-15,9207,"VALLE DE HECHO, HECHO",HUESCA,860,"8,5","0,0","5,0","12,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.750556,42.740556
4246665,2014-11-06,8503Y,TORREBLANCA,CASTELLON,35,"14,6","0,0","8,9","20,3","1,9",NaN,NaN,NaN,50.0,4.0,"8,6",65.0,30.0,0.183611,40.211389
1029390,1991-08-05,2465,SEGOVIA,SEGOVIA,1008,"27,7","0,0","19,5","35,9","2,2","12,3","906,9","904,4",33.0,29.0,"8,9",NaN,NaN,-4.126389,40.945278
4546397,2015-11-01,1038X,AZPEITIA,GIPUZKOA,180,"16,8","0,0","11,9","21,8","0,8",NaN,NaN,NaN,57.0,10.0,"8,1",84.0,46.0,-2.267222,43.1725
1800478,2001-12-26,B278,"PALMA DE MALLORCA, AEROPUERTO",BALEARES,5,"7,8","0,0","0,3","15,2","3,1","8,4","1018,3","1011,8",62.0,31.0,"12,8",NaN,NaN,2.736667,39.560833
5782261,2019-10-30,4260,PERALEDA DEL ZAUCEJO,BADAJOZ,542,"16,0","0,0","8,8","23,1","1,4",NaN,NaN,NaN,70.0,27.0,"8,1",98.0,48.0,-5.5775,38.479722
3172337,2011-01-22,3536X,HOYOS,CACERES,560,"3,4","0,0","-1,2","8,1","2,5",NaN,NaN,NaN,43.0,1.0,"8,6",54.0,30.0,-6.724444,40.174722
547692,1982-06-21,0252D,ARENYS DE MAR,BARCELONA,74,"23,2",Ip,"19,3","27,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.54,41.587222
6241735,2021-04-18,1078C,BALMASEDA,BIZKAIA,210,"8,8","0,0","-0,3","18,0",NaN,NaN,NaN,NaN,64.0,NaN,NaN,95.0,41.0,-3.209722,43.180556
2903758,2010-01-08,B334X,LLUCMAJOR,ILLES BALEARS,140,"7,4","14,0","2,9","11,9",NaN,NaN,NaN,NaN,92.0,NaN,NaN,98.0,81.0,2.891667,39.495556
1268431,1995-02-23,7031,SAN JAVIER AEROPUERTO,MURCIA,4,"13,7","0,0","10,4","17,0","3,3","8,0","1023,6","1020,4",78.0,18.0,"9,7",NaN,NaN,-0.803333,37.788889
805768,1987-09-09,3168C,"GUADALAJARA, EL SERRANILLO",GUADALAJARA,639,"24,2","0,0","13,5","35,0","1,7","10,3","944,9","940,1",46.0,29.0,"7,5",NaN,NaN,-3.173333,40.659167
7190679,2024-04-07,9946X,HORTA DE SANT JOAN,TARRAGONA,495,"21,6","0,0","16,0","27,1",NaN,NaN,NaN,NaN,39.0,NaN,NaN,66.0,23.0,0.311667,40.953056
2425657,2007-05-08,1283U,CABO BUSTO,ASTURIAS,60,"14,4","0,0","11,9","17,0","1,9",NaN,"1022,2","1019,9",81.0,29.0,"7,2",91.0,75.0,-6.47,43.569167
2024433,2004-03-27,4642E,"HUELVA, RONDA ESTE",HUELVA,18,"12,4","1,6","8,8","16,0","5,0","0,4","1003,9","999,8",79.0,17.0,"13,3",NaN,NaN,-6.911667,37.278333
1483546,1998-01-29,C917E,"EL PINAR, LA DEHESA",STA. CRUZ DE TENERIFE,713,"12,1","0,0","10,2","14,0",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-18.115,27.725278
3824767,2013-05-31,5246,SANTA ELENA,JAEN,770,"16,5","0,0","10,6","22,4","5,0","10,6","931,9","928,7",36.0,1.0,"14,2",61.0,18.0,-3.535278,38.344444

### Preprocesado del Dataframe

In [5]:
df_prep = df.copy(deep = True)

In [6]:
# Eliminamos las filas de precipitación acumulada, y cambiamos los valores 'Ip' por 0 (Ip = inferior a 0,1 mm)
df_prep = df_prep[df_prep[const.COL_PREC] != 'Acum']
df_prep[const.COL_PREC] = df_prep[const.COL_PREC].replace('Ip', 0)

In [7]:
# Reemplazamos las comas por puntos para poder cargar los números como decimales (floats)
df_prep[const.COLS_VARIABLES] = df_prep[const.COLS_VARIABLES].replace(',', '.', regex=True).apply(pd.to_numeric, errors = 'raise')

In [8]:
df_prep.dtypes

fecha         datetime64[ns]
indicativo    string[python]
nombre        string[python]
provincia     string[python]
altitud                Int64
tmed                 float64
prec                 float64
tmin                 float64
tmax                 float64
velmedia             float64
sol                  float64
presMax              float64
presMin              float64
hrMedia              float64
dir                  float64
racha                float64
hrMax                float64
hrMin                float64
lon                  Float64
lat                  Float64
dtype: object

In [9]:
# Corregimos inconsistencias en nombres de provincias
df_prep.loc[df_prep[const.COL_PROVINCIA] == 'BALEARES', const.COL_PROVINCIA] = 'ILLES BALEARS'
df_prep.loc[df_prep[const.COL_PROVINCIA] == 'STA. CRUZ DE TENERIFE', const.COL_PROVINCIA] = 'SANTA CRUZ DE TENERIFE'

In [10]:
# Borramos dos datos de una medición anómala
df_prep.loc[
    (df_prep[const.COL_INDICATIVO] == '6084X') &
    (df_prep[const.COL_TMIN] == 50.0) &
    (df_prep[const.COL_TMAX] == -50.0),
    [const.COL_TMIN, const.COL_TMAX]
] = np.nan

In [11]:
# Dejamos a NaN aquellos valores desconocidos (88: 'Desconocida') o múltiples (99: 'Varias), según el fichero de metadatos
df[const.COL_DIR] = df[const.COL_DIR].replace([99, 88], np.nan)

In [12]:
df_prep.sample(20)

,fecha,indicativo,nombre,provincia,altitud,tmed,prec,tmin,tmax,velmedia,sol,presMax,presMin,hrMedia,dir,racha,hrMax,hrMin,lon,lat
6889724,2023-05-02,9546B,HIJAR,TERUEL,305,19.6,0.0,8.7,30.6,1.1,NaN,NaN,NaN,22.0,24.0,6.4,49.0,9.0,-0.441944,41.171944
1004662,1991-03-09,0341,TONA (ESCOLA),BARCELONA,611,9.6,0.0,4.0,15.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.226667,41.846667
4439276,2015-06-25,4263X,VALSEQUILLO,CORDOBA,575,23.6,0.0,13.2,34.1,2.2,NaN,NaN,NaN,26.0,12.0,9.7,68.0,16.0,-5.350556,38.409444
1673335,2000-06-28,6325O,ALMERÍA AEROPUERTO,ALMERIA,21,24.6,0.0,21.4,27.8,2.5,10.8,1014.6,1010.6,73.0,19.0,7.2,NaN,NaN,-2.356944,36.846389
1218569,1994-06-13,0201D,"BARCELONA, PORT OLÍMPIC",BARCELONA,26,18.1,0.0,14.6,21.6,5.6,NaN,1018.7,1016.1,56.0,99.0,11.4,64.0,49.0,2.2,41.390556
248588,1976-01-12,8175,ALBACETE BASE AÉREA,ALBACETE,702,5.4,0.0,-3.2,14.0,1.1,8.0,948.9,944.3,74.0,14.0,3.9,NaN,NaN,-1.856389,38.954167
1099415,1992-09-14,3260B,TOLEDO,TOLEDO,513,24.2,0.0,14.0,34.5,1.9,10.6,960.5,957.6,32.0,27.0,9.4,NaN,NaN,-4.045278,39.884722
389955,1979-01-16,3129,MADRID AEROPUERTO,MADRID,609,4.7,0.0,-0.6,10.0,0.0,3.6,954.7,950.1,85.0,7.0,2.2,NaN,NaN,-3.555556,40.466667
148738,1973-10-22,3200,GETAFE,MADRID,620,13.7,0.0,7.8,19.6,1.7,10.4,953.2,950.6,58.0,NaN,NaN,NaN,NaN,-3.722222,40.299444
4583545,2015-12-16,1060X,AMURRIO,ARABA/ALAVA,240,15.8,0.0,10.6,20.9,1.4,NaN,NaN,NaN,54.0,15.0,10.0,77.0,38.0,-3.005556,43.050278
4896890,2016-12-23,B954,"IBIZA, AEROPUERTO",ILLES BALEARS,6,12.3,0.0,7.4,17.2,1.7,8.8,1034.2,1032.0,86.0,99.0,4.7,98.0,68.0,1.384444,38.876389
2617665,2008-09-14,2946X,SAELICES EL CHICO,SALAMANCA,680,16.6,0.0,7.2,26.0,1.9,NaN,940.8,937.6,45.0,6.0,6.4,75.0,29.0,-6.6,40.635
3046564,2010-07-30,6057X,MANILVA,MALAGA,140,25.6,0.0,22.4,28.9,1.7,NaN,NaN,NaN,68.0,99.0,10.3,93.0,51.0,-5.26,36.378333
2547217,2008-03-31,6032B,RONDA,MALAGA,766,10.2,0.0,4.2,16.2,1.9,NaN,938.8,935.5,54.0,28.0,9.4,85.0,36.0,-5.168333,36.749722
4634496,2016-02-15,8050X,JÁVEA/ XÀBIA,ALICANTE,15,12.5,4.6,8.4,16.6,4.4,9.3,1017.9,1000.0,40.0,29.0,16.7,78.0,28.0,0.166667,38.784167
5593332,2019-03-23,1435C,NOIA,A CORUÑA,128,14.7,0.0,8.0,21.4,1.1,NaN,NaN,NaN,55.0,30.0,5.0,84.0,39.0,-8.876111,42.800278
6737282,2022-11-09,9657X,ESTERRI D'ÀNEU,LLEIDA,952,12.2,0.0,6.7,17.7,1.7,NaN,NaN,NaN,68.0,30.0,7.2,95.0,43.0,1.126111,42.625
3024796,2010-06-30,0421X,ESPOLLA,GIRONA,100,27.8,0.0,22.4,33.3,2.5,NaN,NaN,NaN,43.0,34.0,10.0,70.0,35.0,3.006111,42.39
5974965,2020-06-12,2182C,PEDRAZA,SEGOVIA,1107,10.2,0.0,5.9,14.5,6.9,NaN,NaN,NaN,69.0,27.0,14.2,84.0,51.0,-3.790278,41.133889
2141097,2005-03-24,C459Z,PUERTO DE LA CRUZ,SANTA CRUZ DE TENERIFE,25,19.2,0.0,15.3,23.0,1.1,NaN,NaN,NaN,64.0,6.0,7.2,74.0,53.0,-16.548333,28.418056

In [13]:
display(df_prep.describe().style.format({col: "{:.2f}" for col in df_prep.columns if col != const.COL_FECHA})) # Formateamos todo con 2 decimales excepto la fecha

In [14]:
df_prep.to_csv(const.PATH_DF_PROCESADO, sep = ';', index = False)